# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d0c67e56d0e89d248ba3b9b5524e5c141dc1e92398cb58565eeb147a916dfa7cc095a928cfd25737c59d8bf8cbd477e8fef9c4e1845e7ddac8df1b14cf8fac

test:
  secret_key_base: 409baf12af1a9bffd2c178d190b74f03aa857d0fe16343c9cd9e5ef15481cc3a85d9b5d32e6f833f8b0d9f158fc987696afffb66fcbdd2c16f48ec0111930f11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
